apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ndek
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-ndek@sha256:b9726e0bc47773b8d7f82a9f39bb1516517cc95ef37dd50f865d71376b6eb60f
        name: my-nodejs
        resources: {}
status: {}
